<?php
/**
 * Copyright © 2016 SW-THEMES. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Smartwave\Megamenu\Helper\Data');
    $_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
    
    $urls = array("My Account Home" => $this->getUrl("customer/account/"),"Product" => $this->getUrl(),"My orders" => $this->getUrl("sales/order/history/"),"My Wishlists" => $this->getUrl("wishlist/") ,"Invoices and Payments" => $this->getUrl("") ,"My quotes" => $this->getUrl("") ,"Account setup" => $this->getUrl("customer/account/edit/"));
    $icons = array("Home.png", "Products.png","MyOrders.png","Multiple Wishlist.png","Bills & Payments.png","My Quote.png","Account Setup.png");

    $custom_styles='<style type="text/css">';
?>
<?php if($_portohelper->getConfig('porto_settings/general/layout') == "full_width" && $_portohelper->getConfig('porto_settings/general/category_list_on_left')): ?>

    <div class="onepage-cat category-list">
        <ul>
        <?php
            $i = 0;
            foreach($urls as $name => $url) {
                $cat_id = $i;
				
                $icon = '<em class="porto-icon-circle-empty"></em>';
				
				echo '<li data-index="'.$i.'"><a href="'.$url.'" data-cat="'.$i.'"><img src="'.$this->getViewFileUrl('images/'.$icons[$i]).'"><span>'.$name.'</span></a></li>';
				$i++;
                
            }
        ?>
        </ul>
        <?php
            $custom_styles .= '</style>';
            echo $custom_styles;
        ?>
    </div>
	
    <script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function(){
        $("#maincontent .columns").before($(".onepage-cat.category-list").detach());
        $("#maincontent").addClass("onepage-category");
        $(".onepage-cat.category-list > ul > li > a").each(function(){
            var href = $(this).attr("href");
            if(href.indexOf(window.location.pathname) > -1)
                $(this).addClass("active");
        });
        $(".onepage-category .columns").css("min-height", $(".onepage-cat.category-list").height());
        $(window).scroll(function(){
            if($(".onepage-cat.category-list > ul").outerHeight() < $(this).innerHeight()) {
                $(".onepage-cat.category-list > ul").removeClass("fixed-bottom");
                if($(this).scrollTop() >= $(".onepage-cat.category-list").offset().top + 46) {
                    $(".onepage-cat.category-list > ul").addClass("fixed-top");
                } else {
                    $(".onepage-cat.category-list > ul").removeClass("fixed-top");
                }
            } else {
                $(".onepage-cat.category-list > ul").removeClass("fixed-top");
                if($(this).scrollTop() >= $(".onepage-cat.category-list").offset().top + $(".onepage-cat.category-list > ul").height() + 46 - $(this).innerHeight()) {
                    $(".onepage-cat.category-list > ul").addClass("fixed-bottom");
                } else {
                    $(".onepage-cat.category-list > ul").removeClass("fixed-bottom");
                }
            }
            if(($(".onepage-cat.category-list > ul").hasClass("fixed-bottom") && ($(this).scrollTop() + $(window).innerHeight() >= $(".page-footer").offset().top)) || ($(".onepage-cat.category-list > ul").hasClass("fixed-top") && ($(this).scrollTop() + $(window).innerHeight() >= $(".page-footer").offset().top) && ($(".onepage-cat.category-list > ul").offset().top + $(".onepage-cat.category-list > ul").outerHeight() >= $(".page-footer").offset().top) && ($(this).scrollTop() + $(".onepage-cat.category-list > ul").outerHeight() + 70 >= $(".page-footer").offset().top))) {
                $(".onepage-cat.category-list > ul").addClass("absolute-bottom");
            } else {
                $(".onepage-cat.category-list > ul").removeClass("absolute-bottom");
            }
        });
    });
});
</script>
</div>
<?php endif; ?>